// backend/util/pptxGenerator.js
// The user will need to install pptxgenjs: npm install pptxgenjs
const pptxgen = require('pptxgenjs');

/**
 * Generates a simple PowerPoint presentation.
 * @returns {Promise<string>} A promise that resolves with the base64 content of the presentation.
 */
async function generateSimplePPTX() {
  const pptx = new pptxgen();
  
  // Add a slide
  const slide = pptx.addSlide();

  // Add a title
  slide.addText('Hello World from pptxgenjs!', { 
    x: 1, 
    y: 1, 
    w: '80%', 
    h: 1, 
    fontSize: 36, 
    bold: true, 
    color: '363636' 
  });

  // Add some content
  slide.addText('This is a simple presentation generated with pptxgenjs.', { 
    x: 1, 
    y: 2.5, 
    w: '80%', 
    h: 0.5, 
    fontSize: 18, 
    color: '363636' 
  });

  // Generate the presentation and return it as a base64 string
  return pptx.write('base64');
}

/**
 * Generates a PowerPoint presentation from structured data.
 * @param {object} data The presentation data from the AI.
 * @param {string} data.title The main title of the presentation.
 * @param {Array<object>} data.slides The slides of the presentation.
 * @param {string} data.slides.title The title of a slide.
 * @param {Array<string>} data.slides.bullets The bullet points for a slide.
 * @returns {Promise<string>} A promise that resolves with the base64 content of the presentation.
 */
async function generatePresentation(data) {
  const pptx = new pptxgen();

  // Define a master slide for branding/consistency if needed in the future
  pptx.defineLayout({ name: 'A4', width: 11.69, height: 8.27 });
  pptx.layout = 'A4';

  // --- TITLE SLIDE ---
  const titleSlide = pptx.addSlide();
  titleSlide.addText(data.title || 'Presentation', {
    x: 0.5,
    y: 2.5,
    w: '90%',
    h: 2,
    align: 'center',
    fontSize: 44,
    bold: true,
    color: '363636',
  });
  titleSlide.addText(`Generated by AI`, {
    x: 0.5,
    y: 5.5,
    w: '90%',
    h: 1,
    align: 'center',
    fontSize: 18,
    color: '7F7F7F',
  });

  // --- CONTENT SLIDES ---
  if (data.slides && Array.isArray(data.slides)) {
    data.slides.forEach(slideData => {
      const slide = pptx.addSlide();

      // Slide Title
      slide.addText(slideData.title || 'Untitled Slide', {
        x: 0.5,
        y: 0.5,
        w: '90%',
        h: 1,
        fontSize: 28,
        bold: true,
        color: '363636',
      });

      // Slide Bullets
      if (slideData.bullets && Array.isArray(slideData.bullets)) {
        const bulletPoints = slideData.bullets.map(bullet => ({
          text: bullet,
          options: { fontSize: 18, color: '494949' }
        }));

        slide.addText(bulletPoints, {
          x: 0.75,
          y: 1.8,
          w: '85%',
          h: 5.5,
          bullet: true,
          lineSpacing: 30, // Adjust for better readability
        });
      }
    });
  }

  // Generate the presentation and return it as a base64 string
  return pptx.write('base64');
}

module.exports = {
  generateSimplePPTX,
  generatePresentation,
};
